
.align 3
.section .data
.global _num_app
.global app_0_start
.global app_0_end
.global app_1_start
.global app_1_end
.global app_2_start
.global app_2_end
.global app_3_start
.global app_3_end
.global app_4_start
.global app_4_end
.global app_5_start
.global app_5_end
.global app_6_start
.global app_6_end

_num_app:
    .quad 7
    .quad app_0_start
    .quad app_1_start
    .quad app_2_start
    .quad app_3_start
    .quad app_4_start
    .quad app_5_start
    .quad app_6_start
    .quad app_6_end

app_0_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/00hello_world.bin"
app_0_end:

app_1_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/01store_fault.bin"
app_1_end:

app_2_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/02power.bin"
app_2_end:

app_3_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/03priv_inst.bin"
app_3_end:

app_4_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/04priv_csr.bin"
app_4_end:

app_5_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/05yield_a.bin"
app_5_end:

app_6_start:
    .incbin "../user/target/riscv64gc-unknown-none-elf/release/06yield_b.bin"
app_6_end:
